# https://prettier.io/docs/en/options.html
trailingComma: 'es5'
printWidth: 80
tabWidth: 2
semi: true
singleQuote: true
bracketSpacing: true
bracketSameLine: false
endOfLine: auto
arrowParens: 'always'
